server:
  address: "server:12345"
log:
  level: "INFO"
batch:
  maxAmount: 100
protocol:
  field_separator: ";"
  batch_separator: "~"
  message_delimiter: "\n"
  success_response: "OK"
  failure_response: "FAIL"
data:
  file: "/data/agency.csv"